### PR TITLE
Upgrade to Spark 2.0

### PR DESCRIPTION
**Pull request by snadorp**
Hi,
sorry in advance, this is a massive PR.
I upgraded to use Spark 2.0 but before that, I needed to reformat the sources, somehow there are tabs, 2 and 4 spaces intermixed. I also got rid of the unnecessary mutable state. 
I didn't squash my commits and left them as logical units, so it's easier for you to trace down what changed.

Also upgraded to Scala 2.11, which is the new default for Spark 2.0 but added cross compile capabilities to `build.sbt`
Spark 2.0 made the logging package private, that's why I had to introduce `scala-logging`.

### CODE REVIEW

**Comment by snadorp** [comment]
Any news on this?

**Comment by wchu-citrusleaf** [comment]
This is definitely on our radar. We have some higher priority items to address. We will plan to look at this in a week or two.

**Comment by jaceklaskowski** [comment]
This answer and no way to report issues made me think if I should invest time with the connector. Please help me to get my thoughts calm down and say it's different than I, a newcomer to aerospark, look at things.

See also https://github.com/sasha-polev/aerospark/issues/20

**Comment by rbotzer** [comment]
@jaceklaskowski the [issues](https://github.com/aerospike/aerospark/issues) tab is unlocked now. Please report any bugs in this repo, and direct pull requests to it.

**Pull request merged**
